name: Menu
version: 0.0.1
main: org.oftx.menu.Menu
api-version: '1.20'

dependencies:
  server:
    CMI:
      load: BEFORE
      required: false
    Residence:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false
    floodgate:
      load: BEFORE
      required: true

commands:
  menu:
    description: 菜单
    usage: /menu
    subcommands:
      reload:
        description: 重新加载菜单配置
        usage: /menu reload
        permission: menu.op

permissions:
  menu.op:
    description: Admin of Menu plugin
    default: op